language: php
php:
  - 5.4
  - 5.5
  - 5.6
  #- hhvm
  - nightly

sudo: false

before_script:
  - composer self-update && composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls
